INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:21:49
INFO     | server.py -> accept | new client joined: 49614 |2019-12-13 21:21:49
INFO     | tracker.py -> handle_connection | client connected: 49614 |2019-12-13 21:21:49
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:21:49
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:21:49
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:21:49
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:21:49
INFO     | server.py -> wait_for_termination | server terminated by user |2019-12-13 21:24:07
CRITICAL | server.py -> accept | accept new client failed[Errno 53] Software caused connection abort |2019-12-13 21:24:07
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:24:09
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:24:12
INFO     | server.py -> accept | new client joined: 49624 |2019-12-13 21:24:12
INFO     | tracker.py -> handle_connection | client connected: 49624 |2019-12-13 21:24:12
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:24:12
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:24:12
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:24:12
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:24:12
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:29:13
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:29:15
INFO     | server.py -> wait_for_termination | server terminated by user |2019-12-13 21:31:18
CRITICAL | server.py -> accept | accept new client failed[Errno 53] Software caused connection abort |2019-12-13 21:31:18
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:31:18
INFO     | server.py -> accept | new client joined: 49652 |2019-12-13 21:31:18
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:31:18
INFO     | tracker.py -> handle_connection | client connected: 49652 |2019-12-13 21:31:18
CRITICAL | client.py ->  | receive[Errno 9] Bad file descriptor |2019-12-13 21:31:18
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:31:18
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:31:18
INFO     | server.py -> wait_for_termination | server terminated by user |2019-12-13 21:31:22
CRITICAL | server.py -> accept | accept new client failed[Errno 53] Software caused connection abort |2019-12-13 21:31:22
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:32:35
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:32:38
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:32:38
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:32:38
INFO     | server.py -> accept | new client joined: 49660 |2019-12-13 21:32:38
INFO     | tracker.py -> handle_connection | client connected: 49660 |2019-12-13 21:32:38
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:32:38
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:32:38
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:32:38
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:34:34
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:34:36
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:34:36
INFO     | server.py -> accept | new client joined: 49666 |2019-12-13 21:34:36
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:34:36
INFO     | tracker.py -> handle_connection | client connected: 49666 |2019-12-13 21:34:36
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:34:36
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:34:36
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:34:36
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:35:41
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:35:43
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:35:43
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:35:43
INFO     | server.py -> accept | new client joined: 49673 |2019-12-13 21:35:43
INFO     | tracker.py -> handle_connection | client connected: 49673 |2019-12-13 21:35:43
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:35:43
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:35:43
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:35:43
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:35:43
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:36:53
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:36:56
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:36:56
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:36:56
INFO     | server.py -> accept | new client joined: 49677 |2019-12-13 21:36:56
INFO     | tracker.py -> handle_connection | client connected: 49677 |2019-12-13 21:36:56
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:36:56
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:36:56
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:36:56
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:36:56
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:40:47
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:40:50
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:40:50
INFO     | server.py -> accept | new client joined: 49725 |2019-12-13 21:40:50
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:40:50
INFO     | tracker.py -> handle_connection | client connected: 49725 |2019-12-13 21:40:50
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:40:50
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:40:50
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:40:50
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:40:50
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:44:00
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:44:03
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:44:03
INFO     | server.py -> accept | new client joined: 49735 |2019-12-13 21:44:03
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:44:03
INFO     | tracker.py -> handle_connection | client connected: 49735 |2019-12-13 21:44:03
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:44:03
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:44:03
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:44:03
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:44:03
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:45:33
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:45:35
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:45:35
INFO     | server.py -> accept | new client joined: 49739 |2019-12-13 21:45:35
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:45:35
INFO     | tracker.py -> handle_connection | client connected: 49739 |2019-12-13 21:45:35
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:45:35
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:45:35
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:45:35
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:45:35
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:46:43
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:46:46
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:46:46
INFO     | server.py -> accept | new client joined: 49749 |2019-12-13 21:46:46
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:46:46
INFO     | tracker.py -> handle_connection | client connected: 49749 |2019-12-13 21:46:46
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:46:46
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:46:46
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:46:46
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:46:46
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:48:13
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:48:15
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:48:15
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:48:15
INFO     | server.py -> accept | new client joined: 49761 |2019-12-13 21:48:15
INFO     | tracker.py -> handle_connection | client connected: 49761 |2019-12-13 21:48:15
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:48:15
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:48:15
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:48:15
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:48:15
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:48:47
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:48:50
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:48:50
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:48:50
INFO     | server.py -> accept | new client joined: 49766 |2019-12-13 21:48:50
INFO     | tracker.py -> handle_connection | client connected: 49766 |2019-12-13 21:48:50
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:48:50
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:48:50
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:48:50
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:48:50
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:49:41
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:49:44
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:49:44
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:49:44
INFO     | server.py -> accept | new client joined: 49768 |2019-12-13 21:49:44
INFO     | tracker.py -> handle_connection | client connected: 49768 |2019-12-13 21:49:44
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:49:44
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:49:44
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:49:44
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:49:44
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:50:07
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:50:11
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:50:11
INFO     | server.py -> accept | new client joined: 49772 |2019-12-13 21:50:11
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:50:11
INFO     | tracker.py -> handle_connection | client connected: 49772 |2019-12-13 21:50:11
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:50:11
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:50:11
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:50:11
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:50:11
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:50:56
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:50:59
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:50:59
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:50:59
INFO     | server.py -> accept | new client joined: 49776 |2019-12-13 21:50:59
INFO     | tracker.py -> handle_connection | client connected: 49776 |2019-12-13 21:50:59
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:50:59
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:50:59
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:50:59
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:50:59
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:51:19
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:51:22
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:51:22
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:51:22
INFO     | server.py -> accept | new client joined: 49778 |2019-12-13 21:51:22
INFO     | tracker.py -> handle_connection | client connected: 49778 |2019-12-13 21:51:22
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:51:22
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:51:22
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:51:22
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:51:22
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:51:53
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:51:56
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:51:56
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:51:56
INFO     | server.py -> accept | new client joined: 49781 |2019-12-13 21:51:56
INFO     | tracker.py -> handle_connection | client connected: 49781 |2019-12-13 21:51:56
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:51:56
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:51:56
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:51:56
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:51:56
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:53:19
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:53:22
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:53:22
INFO     | server.py -> accept | new client joined: 49811 |2019-12-13 21:53:22
INFO     | tracker.py -> handle_connection | client connected: 49811 |2019-12-13 21:53:22
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:53:22
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:53:22
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:53:22
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:53:22
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:53:22
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:55:11
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:55:14
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:55:14
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:55:14
INFO     | server.py -> accept | new client joined: 49816 |2019-12-13 21:55:14
INFO     | tracker.py -> handle_connection | client connected: 49816 |2019-12-13 21:55:14
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:55:14
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:55:14
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:55:14
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:55:14
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:55:33
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:55:35
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:55:35
INFO     | server.py -> accept | new client joined: 49819 |2019-12-13 21:55:35
INFO     | tracker.py -> handle_connection | client connected: 49819 |2019-12-13 21:55:35
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:55:35
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:55:35
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:55:35
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:55:35
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:55:35
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:56:06
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:56:09
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:56:09
INFO     | server.py -> accept | new client joined: 49823 |2019-12-13 21:56:09
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:56:09
INFO     | tracker.py -> handle_connection | client connected: 49823 |2019-12-13 21:56:09
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:56:09
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:56:09
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:56:09
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:56:09
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:56:47
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:56:49
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:56:49
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:56:49
INFO     | server.py -> accept | new client joined: 49827 |2019-12-13 21:56:49
INFO     | tracker.py -> handle_connection | client connected: 49827 |2019-12-13 21:56:49
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:56:49
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:56:49
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:56:49
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:56:49
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:57:31
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:57:33
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:57:33
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:57:33
INFO     | server.py -> accept | new client joined: 49832 |2019-12-13 21:57:33
INFO     | tracker.py -> handle_connection | client connected: 49832 |2019-12-13 21:57:33
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:57:33
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:57:33
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:57:33
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:57:33
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 21:59:37
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 21:59:40
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 21:59:40
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 21:59:40
INFO     | server.py -> accept | new client joined: 49841 |2019-12-13 21:59:40
INFO     | tracker.py -> handle_connection | client connected: 49841 |2019-12-13 21:59:40
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 21:59:40
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 21:59:40
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 21:59:40
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 21:59:40
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 22:01:16
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:01:18
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:01:18
INFO     | server.py -> accept | new client joined: 49846 |2019-12-13 22:01:18
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:01:18
INFO     | tracker.py -> handle_connection | client connected: 49846 |2019-12-13 22:01:18
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 22:01:18
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:01:18
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 22:01:18
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 22:01:18
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 22:01:45
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:01:48
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:01:48
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:01:48
INFO     | server.py -> accept | new client joined: 49851 |2019-12-13 22:01:48
INFO     | tracker.py -> handle_connection | client connected: 49851 |2019-12-13 22:01:48
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 22:01:48
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:01:48
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 22:01:48
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 22:01:48
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 22:02:45
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:02:47
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:02:47
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:02:47
INFO     | server.py -> accept | new client joined: 49855 |2019-12-13 22:02:47
INFO     | tracker.py -> handle_connection | client connected: 49855 |2019-12-13 22:02:47
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 22:02:47
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:02:47
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 22:02:47
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 22:02:47
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 22:04:31
CRITICAL | server.py -> listen | server failed with error: [Errno 48] Address already in use |2019-12-13 22:04:31
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 22:06:04
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:06:07
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:06:07
INFO     | server.py -> accept | new client joined: 49863 |2019-12-13 22:06:07
INFO     | tracker.py -> handle_connection | client connected: 49863 |2019-12-13 22:06:07
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:06:07
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:06:07
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 22:06:07
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 22:06:07
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 22:06:07
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 22:06:46
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:06:49
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:06:49
INFO     | server.py -> accept | new client joined: 49865 |2019-12-13 22:06:49
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:06:49
INFO     | tracker.py -> handle_connection | client connected: 49865 |2019-12-13 22:06:49
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 22:06:49
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:06:49
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 22:06:49
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 22:06:49
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 22:07:22
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:07:24
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:07:24
INFO     | server.py -> accept | new client joined: 49869 |2019-12-13 22:07:24
INFO     | tracker.py -> handle_connection | client connected: 49869 |2019-12-13 22:07:24
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:07:24
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:07:24
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 22:07:24
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 22:07:24
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 22:07:24
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 22:09:24
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:09:27
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:09:27
INFO     | server.py -> accept | new client joined: 49874 |2019-12-13 22:09:27
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:09:27
INFO     | tracker.py -> handle_connection | client connected: 49874 |2019-12-13 22:09:27
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 22:09:27
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:09:27
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 22:09:27
INFO     | server.py -> send | data sent{'socket_id': '49874', 'my_ip': '127.0.0.1', 'swarm': <swarm.Swarm object at 0x1098c7860>} |2019-12-13 22:09:27
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 22:09:27
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 22:10:37
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:10:39
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:10:39
INFO     | server.py -> accept | new client joined: 49879 |2019-12-13 22:10:39
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:10:39
INFO     | tracker.py -> handle_connection | client connected: 49879 |2019-12-13 22:10:39
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 22:10:39
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:10:39
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 22:10:39
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None |2019-12-13 22:10:39
INFO     | server.py -> send | data sent{'socket_id': '49879', 'my_ip': '127.0.0.1', 'swarm': <swarm.Swarm object at 0x109fa8f98>} |2019-12-13 22:10:39
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:12:54
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:12:54
INFO     | server.py -> accept | new client joined: 49901 |2019-12-13 22:12:54
INFO     | tracker.py -> handle_connection | client connected: 49901 |2019-12-13 22:12:54
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:12:54
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:12:54
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 22:12:54
FATAL    | client.py -> receive | an exception occured and receive is returning empty data!!! |2019-12-13 22:12:54
INFO     | server.py -> send | data sent{'socket_id': '49901', 'my_ip': '127.0.0.1', 'swarm': <swarm.Swarm object at 0x109fa8f98>} |2019-12-13 22:12:54
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:20:29
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:20:29
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:20:29
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 22:20:29
INFO     | server.py -> accept | new client joined: 49944 |2019-12-13 22:20:29
INFO     | tracker.py -> handle_connection | client connected: 49944 |2019-12-13 22:20:29
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:20:29
INFO     | server.py -> send | data sent{'socket_id': '49944', 'my_ip': '127.0.0.1', 'swarm': <swarm.Swarm object at 0x109fa8f98>} |2019-12-13 22:20:29
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:23:31
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:23:31
INFO     | server.py -> accept | new client joined: 49956 |2019-12-13 22:23:31
INFO     | tracker.py -> handle_connection | client connected: 49956 |2019-12-13 22:23:31
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:23:31
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:23:31
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 22:23:31
INFO     | server.py -> send | data sent{'socket_id': '49956', 'my_ip': '127.0.0.1', 'swarm': <swarm.Swarm object at 0x109fa8f98>} |2019-12-13 22:23:31
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:24:11
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:24:11
INFO     | server.py -> accept | new client joined: 49959 |2019-12-13 22:24:11
INFO     | tracker.py -> handle_connection | client connected: 49959 |2019-12-13 22:24:11
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:24:11
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 22:24:11
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:24:11
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None'NoneType' object is not subscriptable |2019-12-13 22:24:11
INFO     | server.py -> send | data sent{'socket_id': '49959', 'my_ip': '127.0.0.1', 'swarm': <swarm.Swarm object at 0x109fa8f98>} |2019-12-13 22:24:11
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:24:33
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:24:33
INFO     | server.py -> accept | new client joined: 49961 |2019-12-13 22:24:33
INFO     | tracker.py -> handle_connection | client connected: 49961 |2019-12-13 22:24:33
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:24:33
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:24:33
CRITICAL | client.py ->  | receive[Errno 57] Socket is not connected |2019-12-13 22:24:33
INFO     | server.py -> send | data sent{'socket_id': '49961', 'my_ip': '127.0.0.1', 'swarm': <swarm.Swarm object at 0x109fa8f98>} |2019-12-13 22:24:33
FATAL    | peer.py -> connect_to_tracker |  data from tracker: None'NoneType' object is not subscriptable |2019-12-13 22:24:33
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:27:50
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:27:50
INFO     | server.py -> accept | new client joined: 49971 |2019-12-13 22:27:50
INFO     | tracker.py -> handle_connection | client connected: 49971 |2019-12-13 22:27:50
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:27:50
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:27:50
INFO     | server.py -> send | data sent{'socket_id': '49971', 'my_ip': '127.0.0.1', 'swarm': <swarm.Swarm object at 0x109fa8f98>} |2019-12-13 22:27:50
INFO     | client.py -> receive | received data: {'socket_id': '49971', 'my_ip': '127.0.0.1', 'swarm': <swarm.Swarm object at 0x10a094be0>} |2019-12-13 22:27:50
INFO     | server.py -> listen | Listening On 127.0.0.1:13000 |2019-12-13 22:28:08
INFO     | server.py -> listen | Listening On 127.0.0.1:5000 |2019-12-13 22:28:11
INFO     | client.py -> connect | connected to host: 127.0.0.1:13000 |2019-12-13 22:28:11
INFO     | server.py -> accept | new client joined: 49973 |2019-12-13 22:28:11
INFO     | client.py -> send | data sent{'resource_id': 'P2P.pdf'} |2019-12-13 22:28:11
INFO     | tracker.py -> handle_connection | client connected: 49973 |2019-12-13 22:28:11
INFO     | server.py -> receive | received data: {'resource_id': 'P2P.pdf'} |2019-12-13 22:28:11
INFO     | server.py -> send | data sent{'socket_id': '49973', 'my_ip': '127.0.0.1', 'swarm': <swarm.Swarm object at 0x10b291f60>} |2019-12-13 22:28:11
INFO     | client.py -> receive | received data: {'socket_id': '49973', 'my_ip': '127.0.0.1', 'swarm': <swarm.Swarm object at 0x10efb6748>} |2019-12-13 22:28:11
